CDL_FIRST_MATCH_DATE = '2023-12-07'
CDL_YEAR = 2023
BREAKING_POINT_URL = 'https://www.breakingpoint.gg/matches/'

HARDPOINT_TARGET_SCORE = 250
SEARCH_AND_DESTROY_TARGET_SCORE = 6
CONTROL_TARGET_SCORE = 3
