"""Player rankings to Player entity added

Revision ID: 04408ce6f59f
Revises: 
Create Date: 2024-04-09 13:53:23.528089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04408ce6f59f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hardpoint_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('search_and_destroy_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('control_rank', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('control_rank')
        batch_op.drop_column('search_and_destroy_rank')
        batch_op.drop_column('hardpoint_rank')

    # ### end Alembic commands ###
